"""Add cascade delete for mtm

Revision ID: 5266436e5d5c
Revises: fa924ef68e1f
Create Date: 2025-11-16 12:41:25.497177

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5266436e5d5c"
down_revision: Union[str, Sequence[str], None] = "fa924ef68e1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("genre_title_table_title_id_fkey"), "genre_title_table", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("genre_title_table_genre_id_fkey"), "genre_title_table", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "genre_title_table", "genres", ["genre_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "genre_title_table", "titles", ["title_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("tag_title_table_tag_id_fkey"), "tag_title_table", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("tag_title_table_title.id_fkey"), "tag_title_table", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "tag_title_table", "titles", ["title.id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "tag_title_table", "tags", ["tag_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tag_title_table", type_="foreignkey")
    op.drop_constraint(None, "tag_title_table", type_="foreignkey")
    op.create_foreign_key(
        op.f("tag_title_table_title.id_fkey"),
        "tag_title_table",
        "titles",
        ["title.id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("tag_title_table_tag_id_fkey"),
        "tag_title_table",
        "tags",
        ["tag_id"],
        ["id"],
    )
    op.drop_constraint(None, "genre_title_table", type_="foreignkey")
    op.drop_constraint(None, "genre_title_table", type_="foreignkey")
    op.create_foreign_key(
        op.f("genre_title_table_genre_id_fkey"),
        "genre_title_table",
        "genres",
        ["genre_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("genre_title_table_title_id_fkey"),
        "genre_title_table",
        "titles",
        ["title_id"],
        ["id"],
    )
    # ### end Alembic commands ###
