"""User model

Revision ID: 709b564e4c96
Revises: 5266436e5d5c
Create Date: 2025-11-26 16:55:30.723469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709b564e4c96'
down_revision: Union[str, Sequence[str], None] = '5266436e5d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('pseodunym', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'authors', type_='unique')
    op.create_unique_constraint(op.f('authors_pseodunym_key'), 'authors', ['pseodunym'], postgresql_nulls_not_distinct=False)
    op.drop_column('authors', 'pseudunym')
    op.drop_table('users')
    # ### end Alembic commands ###
