"""Initial models

Revision ID: e66b9811c364
Revises: 
Create Date: 2025-10-11 19:23:06.828672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import os


# revision identifiers, used by Alembic.
revision: str = 'e66b9811c364'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('pseudunym', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('pseudunym'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('publishers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('another_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('another_name'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('alternative_title', sa.String(length=255), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('MANGA', 'MANHWA', 'MANHUA', 'OEL_MANGA', name='typeenum', create_type=False), nullable=False),
    sa.Column('status', sa.Enum('ONGOING', 'COMPLETED', 'DISCONTINUED', 'ANNOUNCED', name='statusenum', create_type=False), nullable=False),
    sa.Column('release_format', sa.Enum('YONKOMA', 'ANTHOLOGY', 'DOUJINSHI', 'COLORED', 'ONE_SHOT', 'WEB', 'WEBTOON', name='releaseenum', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alternative_title'),
    sa.UniqueConstraint('slug')
    )
    
    current_dir = os.path.dirname(__file__)
    sql_path = os.path.abspath(os.path.join(current_dir, '../../../'))
    genre_sql = os.path.join(sql_path, 'sql_data', 'genres.sql')
    tag_sql = os.path.join(sql_path, 'sql_data', 'tags.sql')

    with open(genre_sql, encoding='utf-8') as f:
        genres = f.read()
        op.execute(genres)

    with open(tag_sql, encoding='utf-8') as f:
        tags = f.read()
        op.execute(tags)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('titles')
    op.drop_table('tags')
    op.drop_table('publishers')
    op.drop_table('genres')
    op.drop_table('authors')
    # ### end Alembic commands ###
