services:
  database:
    image: postgres:16
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    container_name: backend
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    
  redis:
    image: redis:7
    restart: always
    container_name: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    build: 
      context: .
    container_name: celery_worker
    volumes:
      - .:/app
    restart: always
    command: uv run celery -A backend.shitsu.core.celery worker --loglevel=info
    depends_on:
      - database
      - redis

  # flower:
  #   build:
  #     context: .
  #   container_name: flower
  #   ports:
  #     - "5555:5555"
  #   command: uv run celery -A backend.shitsu.core.celery flower --port=5555
  #   environment:
  #   - PYTHONPATH=/app  
  #   env_file:
  #     - .env
  #   depends_on:
  #     - redis
  #     - celery
  #   restart: always

volumes:
  postgres_data: