services:
  database:
    image: postgres:16
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    container_name: backend
    depends_on:
      - database
      - redis
    
  redis:
    image: redis:7
    restart: always
    container_name: redis

volumes:
  postgres_data: