INSERT INTO genres (name)
VALUES 
  ('Action'),
  ('Adventure'),
  ('Comedy'),
  ('Drama'),
  ('Fantasy'),
  ('Horror'),
  ('Mystery'),
  ('Romance'),
  ('Sci-Fi'),
  ('Slice of Life'),
  ('Thriller'),
  ('Historical'),
  ('Sports'),
  ('Psychological'),
  ('Mecha'),
  ('Seinen'),
  ('Shoujo'),
  ('Shounen'),
  ('Crime'),
  ('Detective'),
  ('Family'),
  ('Friendship'),
  ('Game'),
  ('Isekai'),
  ('Parody'),
  ('Philosophical'),
  ('Political'),
  ('Romantic Comedy'),
  ('Samurai'),
  ('School'),
  ('Space'),
  ('Spy'),
  ('Strategy'),
  ('Suspense'),
  ('War'),
  ('Western');