INSERT INTO tags (name)
VALUES
  ('Aliens'),
  ('Anti-Hero'),
  ('Apocalypse'),
  ('Cyberpunk'),
  ('Demons'),
  ('Dragons'),
  ('Dystopia'),
  ('Gore'),
  ('Magic'),
  ('Military'),
  ('Monsters'),
  ('Parallel Universe'),
  ('Politics'),
  ('Post-Apocalypse'),
  ('Revenge'),
  ('School Life'),
  ('Survival'),
  ('Tragedy'),
  ('Vampires'),
  ('Zombies'),
  ('Chibi'),
  ('Epic'),
  ('Fantasy World'),
  ('Ghosts'),
  ('Super Powers'),
  ('Virtual Reality');