"""Add relationship between tables

Revision ID: d6431b9c3e3d
Revises: e66b9811c364
Create Date: 2025-10-12 12:47:28.593818

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6431b9c3e3d"
down_revision: Union[str, Sequence[str], None] = "e66b9811c364"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genre_title_table",
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genres.id"],
        ),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["titles.id"],
        ),
        sa.PrimaryKeyConstraint("genre_id", "title_id"),
    )
    op.create_table(
        "tag_title_table",
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("title.id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.ForeignKeyConstraint(
            ["title.id"],
            ["titles.id"],
        ),
        sa.PrimaryKeyConstraint("tag_id", "title.id"),
    )
    op.add_column("titles", sa.Column("author_id", sa.UUID(), nullable=False))
    op.add_column("titles", sa.Column("publisher_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "titles", "publishers", ["publisher_id"], ["id"])
    op.create_foreign_key(None, "titles", "authors", ["author_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "titles", type_="foreignkey")
    op.drop_constraint(None, "titles", type_="foreignkey")
    op.drop_column("titles", "publisher_id")
    op.drop_column("titles", "author_id")
    op.drop_table("tag_title_table")
    op.drop_table("genre_title_table")
    # ### end Alembic commands ###
