"""Add pydantic models and autogenerate slug

Revision ID: fa924ef68e1f
Revises: d6431b9c3e3d
Create Date: 2025-11-02 18:59:25.367880

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa924ef68e1f"
down_revision: Union[str, Sequence[str], None] = "d6431b9c3e3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "authors",
        "image",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=2048),
        existing_nullable=True,
    )
    op.alter_column(
        "publishers",
        "image",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=2048),
        existing_nullable=True,
    )
    op.add_column("titles", sa.Column("cover", sa.String(length=2048), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("titles", "cover")
    op.alter_column(
        "publishers",
        "image",
        existing_type=sa.String(length=2048),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "authors",
        "image",
        existing_type=sa.String(length=2048),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
